import {
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { Info } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { Separator } from "@/components/ui/separator";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { cn } from "@/lib/utils";
import {
  cohortFilterLabels,
  cohortRiskBreakdown,
  heatmapRows,
  journeyFilterLabels,
  journeyGroups,
  managers,
  modules,
  monthlyTrend,
  rangeFilterLabels,
  riskSegments,
  summaryStats,
  weeklyTrend,
} from "./analyticsData";

export type ExportFilterSnapshot = {
  journey: string;
  cohort: string;
  range: string;
  trendMode: "weekly" | "monthly";
};

const maxBar = Math.max(...journeyGroups.flatMap((g) => g.rows.map((r) => r.pct)), 1);

function formatToday() {
  return new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

function filterSummary(snapshot: ExportFilterSnapshot) {
  const noFilters =
    snapshot.journey === "all" && snapshot.cohort === "all" && snapshot.range === "all";
  if (noFilters) return "Showing all data — no filters applied.";
  return `Filtered by: ${journeyFilterLabels[snapshot.journey]} · ${
    cohortFilterLabels[snapshot.cohort]
  } · Date range: ${rangeFilterLabels[snapshot.range]}`;
}

function SectionHeading({ children }: { children: React.ReactNode }) {
  return <h3 className="text-base font-semibold text-foreground">{children}</h3>;
}

export function ExportPreviewDialog({
  open,
  onOpenChange,
  snapshot,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  snapshot: ExportFilterSnapshot | null;
}) {
  if (!snapshot) return null;

  const today = formatToday();
  const trendData = snapshot.trendMode === "monthly" ? monthlyTrend : weeklyTrend;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-5xl max-h-[90vh] overflow-y-auto">
        <Alert>
          <Info className="h-4 w-4" aria-hidden="true" />
          <AlertDescription>
            This is a preview of your export. In the final product, clicking "Export Report" would
            download this report as a formatted PDF file.
          </AlertDescription>
        </Alert>

        <div className="flex items-start justify-between gap-4">
          <div>
            <h2 className="text-2xl font-semibold text-foreground">Admin Analytics Report</h2>
            <p className="mt-1 text-sm text-muted-foreground">{filterSummary(snapshot)}</p>
            <p className="text-sm text-muted-foreground">Report generated: {today}</p>
            <p className="text-sm text-muted-foreground">Generated by: Admin</p>
          </div>
          <Button variant="secondary" onClick={() => onOpenChange(false)}>
            Close Preview
          </Button>
        </div>

        <Separator />

        {/* Summary Statistics */}
        <section className="space-y-4">
          <SectionHeading>Summary Statistics</SectionHeading>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-5">
            {summaryStats.map((stat) => (
              <div key={stat.label} className="rounded-lg border border-border bg-background px-4 py-3">
                <div className="text-[11px] font-semibold tracking-wide text-muted-foreground">
                  {stat.label}
                </div>
                <div className="mt-1 text-2xl font-bold leading-tight text-foreground">
                  {stat.value}
                </div>
                <div className="mt-0.5 text-xs text-muted-foreground">{stat.sub}</div>
              </div>
            ))}
          </div>
        </section>

        <Separator />

        {/* Analytics Overview */}
        <section className="space-y-4">
          <SectionHeading>Analytics Overview</SectionHeading>

          <div className="rounded-lg border border-border bg-background p-5">
            <div className="text-sm font-medium text-foreground">Completion Rate by Cohort</div>
            <div className="mt-4 space-y-4">
              {journeyGroups.map((group) => (
                <div key={group.journey} className="space-y-2">
                  <div className="text-[11px] font-semibold tracking-wide text-muted-foreground border-b border-border pb-1">
                    {group.journey}
                  </div>
                  <div className="space-y-3 pt-1">
                    {group.rows.map((row) => {
                      const relative = row.pct === 0 ? 100 : (row.pct / maxBar) * 100;
                      return (
                        <div key={row.name} className="flex items-center gap-3">
                          <div className="w-48 shrink-0 text-sm text-foreground">{row.name}</div>
                          <div className="h-2.5 flex-1 overflow-hidden rounded-full bg-muted">
                            <div
                              className={cn(
                                "h-full rounded-full",
                                row.pct === 0 ? "bg-muted-foreground/30" : "bg-primary",
                              )}
                              style={{ width: `${relative}%` }}
                            />
                          </div>
                          <div className="w-20 shrink-0 text-right text-xs text-muted-foreground">
                            {row.pct === 0 ? "Not started" : `${row.pct}%`}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              ))}
            </div>
          </div>

          <Separator />

          <div className="rounded-lg border border-border bg-background p-5">
            <div className="text-sm font-medium text-foreground">Learner Risk Distribution</div>
            <div className="mt-4 flex h-3 w-full overflow-hidden rounded-full">
              {riskSegments.map((seg) => (
                <div key={seg.key} className={cn("h-full", seg.bar)} style={{ width: `${seg.pct}%` }} />
              ))}
            </div>
            <div className="mt-4 flex flex-wrap gap-x-4 gap-y-2">
              {riskSegments.map((seg) => (
                <div key={seg.key} className="flex items-center gap-2 text-sm text-foreground">
                  <span className={cn("h-2 w-2 rounded-full", seg.dot)} aria-hidden="true" />
                  <span>
                    {seg.label} <span className="text-muted-foreground">({seg.count})</span>
                  </span>
                </div>
              ))}
            </div>
          </div>

          <Separator />

          <div className="rounded-lg border border-border bg-background p-5">
            <div className="text-sm font-medium text-foreground">
              Completion Trend — Organisation Wide ({snapshot.trendMode === "monthly" ? "Monthly" : "Weekly"})
            </div>
            <div className="mt-4 h-64 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={trendData} margin={{ top: 8, right: 16, bottom: 8, left: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                  <XAxis dataKey="period" tickLine={false} axisLine={false} className="text-xs" />
                  <YAxis tickLine={false} axisLine={false} className="text-xs" />
                  <Tooltip />
                  <Line type="monotone" dataKey="cohortA" stroke="hsl(var(--primary))" strokeWidth={2} dot={false} name="Cohort A" />
                  <Line type="monotone" dataKey="cohortB" stroke="hsl(var(--success))" strokeWidth={2} dot={false} name="Cohort B" />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>

          <Separator />

          <div className="overflow-hidden rounded-lg border border-border bg-background">
            <div className="p-5 pb-0 text-sm font-medium text-foreground">
              Assessment Performance by Module
            </div>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Module</TableHead>
                  <TableHead>Journey</TableHead>
                  <TableHead>Avg Score</TableHead>
                  <TableHead>Submissions</TableHead>
                  <TableHead>Below 65%</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {modules.map((m) => (
                  <TableRow key={m.module}>
                    <TableCell className="text-sm text-foreground">{m.module}</TableCell>
                    <TableCell className="text-xs text-muted-foreground">{m.journey}</TableCell>
                    <TableCell className="text-sm text-foreground">
                      {m.avgScore === null ? "—" : `${m.avgScore}%`}
                    </TableCell>
                    <TableCell className="text-sm text-foreground">{m.submissions}</TableCell>
                    <TableCell className="text-sm text-foreground">
                      {m.below65 === null ? "—" : m.below65}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </section>

        <Separator />

        {/* Manager Performance */}
        <section className="space-y-4">
          <SectionHeading>Manager Performance</SectionHeading>
          <div className="overflow-hidden rounded-lg border border-border bg-background">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Manager</TableHead>
                  <TableHead>Cohorts</TableHead>
                  <TableHead>Total Learners</TableHead>
                  <TableHead>Avg Completion</TableHead>
                  <TableHead>At-Risk Learners</TableHead>
                  <TableHead>Avg Assessment Score</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {managers.map((m) => (
                  <TableRow key={m.id}>
                    <TableCell className="text-sm text-foreground">{m.name}</TableCell>
                    <TableCell className="text-sm text-foreground">{m.cohorts}</TableCell>
                    <TableCell className="text-sm text-foreground">{m.learners}</TableCell>
                    <TableCell className="text-sm text-foreground">{m.completion}%</TableCell>
                    <TableCell className="text-sm text-foreground">{m.atRisk}</TableCell>
                    <TableCell className="text-sm text-foreground">{m.avgScore}%</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </section>

        <Separator />

        {/* Cohort Summary */}
        <section className="space-y-4">
          <SectionHeading>Cohort Summary</SectionHeading>
          <div className="overflow-hidden rounded-lg border border-border bg-background">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Cohort</TableHead>
                  <TableHead>Risk split</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {cohortRiskBreakdown.map((row) => (
                  <TableRow key={row.cohort}>
                    <TableCell className="text-sm text-foreground">{row.cohort}</TableCell>
                    <TableCell>
                      <div className="flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
                        {row.segments.map((s, i) => (
                          <span key={i} className="flex items-center gap-1.5">
                            <span className={cn("h-2 w-2 rounded-full", s.dot)} aria-hidden="true" />
                            <span>{s.count}</span>
                          </span>
                        ))}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>

          <div className="overflow-hidden rounded-lg border border-border bg-background">
            <div className="p-5 pb-0 text-sm font-medium text-foreground">
              Skill Readiness by Cohort
            </div>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Skill</TableHead>
                  <TableHead>Medicare CSR Cohort A</TableHead>
                  <TableHead>Medicare CSR Cohort B</TableHead>
                  <TableHead>New Starter Cohort Q3</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {heatmapRows.map((row) => (
                  <TableRow key={row.skill}>
                    <TableCell className="text-sm text-foreground">{row.skill}</TableCell>
                    {[row.cohortA, row.cohortB, row.q3].map((v, i) => (
                      <TableCell key={i} className="text-sm text-foreground">
                        {v === null ? "—" : `${v}%`}
                      </TableCell>
                    ))}
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </section>

        <Separator />

        <p className="text-xs text-muted-foreground">
          Confidential — generated from Embark Admin Analytics · {today}
        </p>
      </DialogContent>
    </Dialog>
  );
}
