import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { StatTile } from "@/components/embark/StatTile";
import { LeftBorderCard } from "@/components/embark/LeftBorderCard";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { PageContainer } from "@/components/embark/layouts/PageContainer";
import { SessionShell } from "@/components/embark/SessionShell";
import { useAssessmentSettings } from "@/hooks/use-assessment-settings";
import { buildReadinessSteps } from "./readinessSteps";
import { useReadinessProfile } from "@/hooks/use-readiness-profile";

function useAssessmentData() {
  const { activityId = "a8" } = useParams();
  const { content: contentMap, questions: questionsMap, org, findActivity } = useReadinessProfile();
  const activity = findActivity(activityId);
  const id = activityId in questionsMap ? activityId : "a8";
  const isGate = activity?.activityKind === "chapter_gate";
  const retakes = isGate ? 0 : 3;
  return {
    id,
    content: contentMap[id],
    questions: questionsMap[id],
    org,
    activity,
    isGate,
    retakes,
  };
}

function Briefing({ onBegin }: { onBegin: () => void }) {
  const navigate = useNavigate();
  const { id, content, questions, org, activity, isGate, retakes } = useAssessmentData();
  const steps = buildReadinessSteps(id, navigate, org);

  return (
    <SessionShell
      topHeader={null}
      title={`${content.title} — Knowledge Check`}
      subtitle={`${content.moduleName} · Assessment · ~10 min`}
      onBack={() => navigate(`/readiness/activity/${id}`)}
      steps={steps}
      stepsMeta={org === "rathbones" ? "Your role readiness journey" : "Your project readiness journey"}
      positionLabel={content.programName}
      prev={{ label: "Back to session", onClick: () => navigate(`/readiness/session/${id}`) }}
      next={{ label: "Begin assessment", onClick: onBegin }}
      sagePrompts={[
        { label: "What's tested?" },
        { label: "How is it scored?" },
        { label: "Tips for passing" },
        { label: "Raise a hand 🤚" },
      ]}
      sageDisclaimer="Generated by AI. Check for accuracy."
    >
      <div className="flex-1 overflow-y-auto">
        <PageContainer as="div" className="pt-6 sm:pt-8 pb-32 space-y-5">
          <div>
            <h1 className="text-2xl font-bold text-foreground">
              {activity?.name ?? content.title}
            </h1>
            <p className="text-sm text-muted-foreground mt-1">{content.programName}</p>
          </div>
          <div className="grid grid-cols-3 gap-3">
            <StatTile label="Questions" value={String(questions.length)} />
            <StatTile label="To pass" value="80%" />
            <StatTile label="Retakes available" value={String(retakes)} />
          </div>
          <p className="text-sm text-foreground">
            {isGate
              ? "This is a chapter gate. You have one attempt. A score below 80% raises an at-risk flag for your line manager and pauses progress until they check in."
              : "This check uses a pass mark of 80%. You can retake it up to 3 times. After that the journey pauses until your line manager reopens it."}
          </p>
        </PageContainer>
      </div>
    </SessionShell>
  );
}

function QuestionState({ onExit }: { onExit: () => void }) {
  const navigate = useNavigate();
  const { id, content, questions, org, isGate } = useAssessmentData();
  const steps = buildReadinessSteps(id, navigate, org);
  const assessmentSettings = useAssessmentSettings();
  const [currentIndex, setCurrentIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string | null>>(() =>
    Object.fromEntries(questions.map((q) => [q.id, null])),
  );
  const [flagged, setFlagged] = useState<Record<string, boolean>>(() =>
    Object.fromEntries(questions.map((q) => [q.id, false])),
  );

  const current = questions[currentIndex];
  const selected = answers[current.id];
  const isLast = currentIndex === questions.length - 1;
  const allAnswered = questions.every((q) => answers[q.id] != null);

  const handleSubmit = () => {
    const score = questions.reduce((acc, q) => acc + (answers[q.id] === q.correctId ? 1 : 0), 0);
    const total = questions.length;
    const outcome = score / total >= 0.8 ? "pass" : "fail";
    navigate(
      `/readiness/assessment/${id}/results?outcome=${outcome}&score=${score}&total=${total}&gate=${isGate ? "1" : "0"}`,
    );
  };

  const progressPct = ((currentIndex + 1) / questions.length) * 100;

  const footer = (
    <div className="flex items-center justify-between gap-4 h-full">
      <Button
        variant="ghost"
        className="gap-1.5"
        disabled={currentIndex === 0}
        onClick={() => setCurrentIndex((i) => Math.max(0, i - 1))}
      >
        ← Previous
      </Button>
      <div className="text-xs text-muted-foreground hidden sm:block">
        Question {currentIndex + 1} of {questions.length}
      </div>
      {isLast ? (
        <Button disabled={!allAnswered} onClick={handleSubmit}>
          Submit assessment
        </Button>
      ) : (
        <Button
          className="gap-1.5"
          disabled={!selected}
          onClick={() => setCurrentIndex((i) => Math.min(questions.length - 1, i + 1))}
        >
          Next →
        </Button>
      )}
    </div>
  );

  return (
    <SessionShell
      topHeader={null}
      title={`${content.title} — Knowledge Check`}
      subtitle={`Assessment · Question ${currentIndex + 1} of ${questions.length}`}
      onBack={onExit}
      steps={steps}
      stepsMeta={org === "rathbones" ? "Your role readiness journey" : "Your project readiness journey"}
      footer={footer}
      sagePrompts={[
        { label: "Explain this question" },
        { label: "What does the session say about this?" },
        { label: "Give me an example" },
        { label: "Raise a hand 🤚" },
      ]}
    >
      <div className="h-1 w-full bg-muted flex-shrink-0">
        <div
          className="h-full bg-secondary-foreground transition-all"
          style={{ width: `${progressPct}%` }}
        />
      </div>
      <div className="flex-1 overflow-y-auto">
        <PageContainer as="div" className="pt-6 pb-32">
          <div className="rounded-lg border border-border bg-card shadow-sm p-5 sm:p-6 space-y-5">
            {current.scenario ? (
              <LeftBorderCard borderVariant="brand">
                <div className="text-[11px] font-semibold tracking-wide text-muted-foreground mb-1">
                  {current.sectionLabel}
                </div>
                <p className="text-sm text-foreground">{current.scenario}</p>
              </LeftBorderCard>
            ) : (
              <div className="text-[11px] font-semibold tracking-wide text-muted-foreground mb-1">
                {current.sectionLabel}
              </div>
            )}

            <h3 className="text-base font-semibold text-foreground">{current.prompt}</h3>

            <div className="space-y-2">
              {current.options.map((opt) => {
                const isSel = selected === opt.id;
                return (
                  <button
                    key={opt.id}
                    type="button"
                    onClick={() => setAnswers((prev) => ({ ...prev, [current.id]: opt.id }))}
                    className={cn(
                      "w-full text-left rounded-lg border bg-background px-4 py-3 min-h-[44px] transition-colors flex gap-3 items-start",
                      isSel
                        ? "border-primary border-2 bg-secondary/40"
                        : "border-border hover:bg-muted",
                    )}
                  >
                    <span className="text-sm font-semibold text-muted-foreground w-5 flex-shrink-0">
                      {opt.id}
                    </span>
                    <span className="text-sm text-foreground">{opt.text}</span>
                  </button>
                );
              })}
            </div>

            {assessmentSettings.flagForReview && (
              <label className="flex items-center gap-2 text-xs text-muted-foreground cursor-pointer">
                <input
                  type="checkbox"
                  checked={!!flagged[current.id]}
                  onChange={(e) =>
                    setFlagged((prev) => ({ ...prev, [current.id]: e.target.checked }))
                  }
                  className="h-4 w-4 rounded border-border"
                />
                Flag this question for review
              </label>
            )}
          </div>
        </PageContainer>
      </div>
    </SessionShell>
  );
}

export default function ReadinessAssessment() {
  const [state, setState] = useState<"briefing" | "question">("briefing");
  return state === "briefing" ? (
    <Briefing onBegin={() => setState("question")} />
  ) : (
    <QuestionState onExit={() => setState("briefing")} />
  );
}
