import { useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { AlertCircle } from "lucide-react";
import { StatTile } from "@/components/embark/StatTile";
import { CompletionSummary } from "@/components/embark/CompletionSummary";
import { AnswerReviewList } from "@/components/embark/AnswerReviewList";
import { QuestionContent } from "@/components/embark/QuestionContent";
import { modules } from "@/data/mockData";
import { ASSESSMENT_DEFAULTS, type AssessmentConfig } from "@/data/assessmentTypes";
import { questions, questionsForItem } from "@/data/learnerAssessmentQuestions";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { cn } from "@/lib/utils";
import { PageContainer } from "@/components/embark/layouts/PageContainer";
import { SessionShell } from "@/components/embark/SessionShell";
import { buildMod3SessionSteps } from "@/components/embark/session/sessionSteps";
import { useLearnerJourneySteps } from "@/components/embark/session/learnerJourneySteps";
import { useModule3Progress } from "@/hooks/use-module3-progress";
import { useOrganisation } from "@/hooks/use-organisation";
import { attemptAllowance, useAssessmentAttempts } from "@/hooks/use-assessment-attempts";
import { buildMod3Flow } from "@/pages/embark/learner/home/JourneyTabs";

const assessmentConfig = ASSESSMENT_DEFAULTS["Module Assessment"];

export { questions };

function configForKind(kind?: string): AssessmentConfig {
  if (kind === "knowledge_check") return ASSESSMENT_DEFAULTS["Knowledge Check"];
  if (kind === "chapter_gate") return ASSESSMENT_DEFAULTS["Chapter Gate"];
  return ASSESSMENT_DEFAULTS["Module Assessment"];
}

function Briefing({
  onBegin,
  moduleId,
  isReview,
  itemId,
}: {
  onBegin: () => void;
  moduleId: string;
  isReview: boolean;
  itemId: string | null;
}) {
  const navigate = useNavigate();
  const { progress } = useModule3Progress();
  const { org } = useOrganisation();
  const { forItem, paused } = useAssessmentAttempts();
  const journey = useLearnerJourneySteps(itemId);
  const steps = journey?.steps ?? buildMod3SessionSteps("s-assessment", progress, navigate);
  const completedModule = modules.find(
    (m) => m.id === moduleId && m.status === "completed",
  );
  const session = itemId ? buildMod3Flow(progress, org).find((entry) => entry.id === itemId) : undefined;
  const bank = questionsForItem(itemId);
  const typeConfig = configForKind(session?.sessionKind);
  const allowance = attemptAllowance(session?.sessionKind);
  const attempt = forItem(itemId);
  const attemptsRemaining = attempt.paused ? 0 : Math.max(0, allowance - attempt.used);
  const outOfAttempts = attempt.paused;
  const journeyPaused = org === "rathbones" && paused.length > 0;
  const sectionTitle =
    org === "rathbones" && session ? session.name : "Benefits Navigation — Module Assessment";
  const sectionSubtitle =
    org === "rathbones" && journey?.positionLabel
      ? `IM Intake Pathway · ${journey.positionLabel}`
      : "Session 3 of 4 · Assessment · ~10 min";
  return (
    <SessionShell
      title={sectionTitle}
      subtitle={sectionSubtitle}
      onBack={() => navigate("/learner/home")}
      steps={steps}
      stepsMeta={journey?.stepsMeta ?? "Benefits Navigation · Module 3"}
      positionLabel={journey?.positionLabel ?? "Session 3 of 4"}
      prev={
        journeyPaused
          ? null
          : { label: "Previous", onClick: () => navigate("/learner/session/s-video") }
      }
      next={
        isReview
          ? { label: "Completed", disabled: true }
          : outOfAttempts
            ? {
                label: "Journey paused",
                disabled: true,
                disabledReason: "Your line manager needs to check in and reopen this module.",
              }
            : { label: "Begin assessment", onClick: onBegin }
      }
      sagePrompts={[
        { label: "What's tested?" },
        { label: "How is it scored?" },
        { label: "Tips for advancing" },
        { label: "Raise a hand 🤚" },
      ]}
      sageDisclaimer="Generated by AI. Check for accuracy."
    >
      <div className="flex-1 overflow-y-auto">
        <PageContainer as="div" className="pt-6 sm:pt-8 pb-32 space-y-5">
          {isReview && (
            <CompletionSummary
              label="You've already completed this assessment — you're reviewing it now."
              completedDate={completedModule?.completedDate}
              score={completedModule?.score}
            />
          )}
          {outOfAttempts && (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertTitle>Journey paused</AlertTitle>
              <AlertDescription>
                {allowance <= 1
                  ? `${session?.name ?? "This chapter gate"} allows one attempt. A score below 80% has raised an at-risk flag. Your line manager needs to check in before the journey continues.`
                  : `You've used all ${Math.max(0, allowance - 1)} retakes on ${session?.name ?? "this assessment"}. An at-risk flag has been raised, and Sage has asked your line manager to check in. This module stays paused until they reopen it.`}
              </AlertDescription>
            </Alert>
          )}
          <div>
            <h1 className="text-2xl font-bold text-foreground">
              {org === "rathbones" && session ? session.name : "Benefits Navigation — Module Assessment"}
            </h1>
            <p className="text-sm text-muted-foreground mt-1">
              {journey?.positionLabel ?? "Session 3 of 4"}
            </p>
          </div>
          <div className="grid grid-cols-3 gap-3">
            <StatTile label="Questions" value={String(bank.length)} />
            <StatTile label="To advance" value={`${typeConfig.passThreshold}%`} />
            <StatTile
              label="Attempts remaining"
              value={attemptsRemaining == null ? "Unlimited" : String(attemptsRemaining)}
            />
          </div>
          <div className="space-y-1">
            <p className="text-sm text-foreground">{org === "rathbones" && session ? typeConfig.briefing : assessmentConfig.briefing}</p>
          </div>
        </PageContainer>
      </div>
    </SessionShell>
  );
}

function QuestionState({
  onExit,
  moduleId,
  itemId,
}: {
  onExit: () => void;
  moduleId: string;
  itemId: string | null;
}) {
  const navigate = useNavigate();
  const { progress } = useModule3Progress();
  const { org } = useOrganisation();
  const { recordAttempt, paused } = useAssessmentAttempts();
  const bank = questionsForItem(itemId);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [mode, setMode] = useState<"question" | "review">("question");
  const [answers, setAnswers] = useState<Record<string, string | null>>(
    () => Object.fromEntries(bank.map((q) => [q.id, null])),
  );
  const [showValidation, setShowValidation] = useState(false);

  const current = bank[currentIndex];
  const selected = answers[current.id];
  const isLast = currentIndex === bank.length - 1;
  const unanswered = bank
    .map((q, i) => ({ q, i }))
    .filter(({ q }) => answers[q.id] == null);
  const allAnswered = unanswered.length === 0;

  const handleSubmit = () => {
    if (!allAnswered) {
      setShowValidation(true);
      return;
    }
    const score = bank.reduce(
      (acc, q) => acc + (answers[q.id] === q.correctId ? 1 : 0),
      0,
    );
    const total = bank.length;
    const typeConfig = configForKind(
      buildMod3Flow(progress, org).find((entry) => entry.id === itemId)?.sessionKind,
    );
    const outcome = score / total >= typeConfig.passThreshold / 100 ? "pass" : "fail";
    if (org === "rathbones" && itemId) {
      const session = buildMod3Flow(progress, org).find((entry) => entry.id === itemId);
      recordAttempt(itemId, {
        passed: outcome === "pass",
        score,
        total,
        max: attemptAllowance(session?.sessionKind),
        name: session?.name ?? "Assessment",
        kind: session?.sessionKind,
      });
    }
    const itemQuery = itemId ? `&item=${encodeURIComponent(itemId)}` : "";
    navigate(
      `/learner/assessment/${moduleId}/results?outcome=${outcome}&score=${score}&total=${total}${itemQuery}`,
      { state: { answers, questionIds: bank.map((q) => q.id) } },
    );
  };

  const validationAlert = showValidation && !allAnswered && (
    <Alert variant="destructive" role="alert">
      <AlertCircle className="h-4 w-4 flex-shrink-0" />
      <AlertTitle>
        {unanswered.length === 1
          ? "1 question still needs an answer"
          : `${unanswered.length} questions still need an answer`}
      </AlertTitle>
      <AlertDescription>
        <p>Every question must be answered before you can submit.</p>
        <ul className="mt-2 flex flex-wrap gap-2">
          {unanswered.map(({ i }) => (
            <li key={i}>
              <Button
                type="button"
                size="sm"
                variant="outline"
                onClick={() => {
                  setCurrentIndex(i);
                  setMode("question");
                }}
              >
                Question {i + 1}
              </Button>
            </li>
          ))}
        </ul>
      </AlertDescription>
    </Alert>
  );

  const progressPct = ((currentIndex + 1) / bank.length) * 100;
  const journey = useLearnerJourneySteps(itemId);
  const steps = journey?.steps ?? buildMod3SessionSteps("s-assessment", progress, navigate);
  const session = itemId ? buildMod3Flow(progress, org).find((entry) => entry.id === itemId) : undefined;
  const journeyPaused = org === "rathbones" && paused.length > 0;
  const sectionTitle =
    org === "rathbones" && session ? session.name : "Benefits Navigation Assessment";
  const sectionSubtitle =
    org === "rathbones" && journey?.positionLabel
      ? `IM Intake Pathway · ${journey.positionLabel}`
      : mode === "review"
        ? "Session 3 of 4 · Assessment · Review"
        : `Session 3 of 4 · Assessment · Question ${currentIndex + 1} of ${bank.length}`;

  if (mode === "review") {
    const reviewFooter = (
      <div className="flex items-center justify-between gap-4 h-full">
        <Button variant="ghost" onClick={() => { setCurrentIndex(0); setMode("question"); }}>
          Back to beginning
        </Button>
        <div className="text-xs text-muted-foreground hidden sm:block">Review</div>
        <Button
          onClick={handleSubmit}
          disabled={!allAnswered}
          aria-disabled={!allAnswered}
          title={allAnswered ? undefined : "Answer every question to submit"}
        >
          Submit
        </Button>
      </div>
    );
    return (
      <SessionShell
        title={sectionTitle}
        subtitle={sectionSubtitle}
        onBack={() => setMode("question")}
        steps={steps}
        stepsMeta={journey?.stepsMeta ?? "Benefits Navigation · Module 3"}
        footer={reviewFooter}
        sagePrompts={[
          { label: "Explain this question" },
          { label: "Give me an example" },
          { label: "Raise a hand 🤚" },
        ]}
      >
        <div className="h-1 w-full bg-muted flex-shrink-0">
          <div className="h-full bg-secondary-foreground transition-all" style={{ width: "100%" }} />
        </div>
        <div className="flex-1 overflow-y-auto">
          <PageContainer as="div" className="pt-6 pb-32 space-y-4">
            <div>
              <h1 className="text-2xl font-bold text-foreground">Review your answers</h1>
              <p className="text-sm text-muted-foreground mt-1">
                Check your answers before submitting. You can revisit any answer or go back to the beginning.
              </p>
            </div>
            {validationAlert}
            <AnswerReviewList
              questions={bank}
              answers={answers}
              onEdit={(i) => {
                setCurrentIndex(i);
                setMode("question");
              }}
            />
          </PageContainer>
        </div>
      </SessionShell>
    );
  }

  const footer = (
    <div className="flex items-center justify-between gap-4 h-full">
      {journeyPaused ? (
        <span />
      ) : (
        <Button
          variant="ghost"
          className="gap-1.5"
          disabled={currentIndex === 0}
          onClick={() => setCurrentIndex((i) => Math.max(0, i - 1))}
        >
          ← Previous
        </Button>
      )}
      <div className="text-xs text-muted-foreground hidden sm:block">
        Question {currentIndex + 1} of {bank.length}
      </div>
      {isLast ? (
        <Button
          onClick={() => {
            if (!allAnswered) {
              setShowValidation(true);
              return;
            }
            setMode("review");
          }}
          aria-disabled={!allAnswered}
          variant={allAnswered ? "default" : "secondary"}
        >
          Review answers
        </Button>
      ) : (
        <Button
          className="gap-1.5"
          disabled={!selected}
          onClick={() =>
            setCurrentIndex((i) => Math.min(bank.length - 1, i + 1))
          }
        >
          Next →
        </Button>
      )}
    </div>
  );

  return (
    <SessionShell
      title={sectionTitle}
      subtitle={sectionSubtitle}
      onBack={onExit}
      steps={steps}
      stepsMeta={journey?.stepsMeta ?? "Benefits Navigation · Module 3"}
      footer={footer}
      sagePrompts={[
        { label: "Explain COB rules" },
        { label: "What's the Part B deductible?" },
        { label: "When is PA required?" },
        { label: "Difference between Part C and Part D?" },
        { label: "Raise a hand 🤚" },
      ]}
    >
      <div className="h-1 w-full bg-muted flex-shrink-0">
        <div
          className="h-full bg-secondary-foreground transition-all"
          style={{ width: `${progressPct}%` }}
        />
      </div>
      <div className="flex-1 overflow-y-auto">
          <PageContainer as="div" className="pt-6 pb-32 space-y-4">
            {validationAlert}
            <div className="rounded-lg border border-border bg-card shadow-sm p-5 sm:p-6 space-y-5">
              <QuestionContent question={current} />

              <div className="space-y-2">
                {current.options.map((opt) => {
                  const isSel = selected === opt.id;
                  return (
                    <button
                      key={opt.id}
                      type="button"
                      aria-pressed={isSel}
                      onClick={() => {
                        setAnswers((prev) => ({ ...prev, [current.id]: opt.id }));
                        if (unanswered.length <= 1) setShowValidation(false);
                      }}
                      className={cn(
                        "w-full text-left rounded-lg border bg-background px-4 py-3 min-h-[44px] transition-colors flex gap-3 items-start",
                        isSel
                          ? "border-primary border-2 bg-secondary/40"
                          : "border-border hover:bg-muted",
                      )}
                    >
                      <span className="text-sm font-semibold text-muted-foreground w-5 flex-shrink-0">
                        {opt.id}
                      </span>
                      <span className="text-sm text-foreground">{opt.text}</span>
                    </button>
                  );
                })}
              </div>
            </div>
          </PageContainer>
      </div>
    </SessionShell>
  );
}

export default function Assessment() {
  const { moduleId = "mod3" } = useParams();
  const [searchParams] = useSearchParams();
  const isReview = searchParams.get("review") === "true";
  const itemId = searchParams.get("item");
  const [state, setState] = useState<"briefing" | "question">("briefing");

  return state === "briefing" ? (
    <Briefing moduleId={moduleId} itemId={itemId} isReview={isReview} onBegin={() => setState("question")} />
  ) : (
    <QuestionState moduleId={moduleId} itemId={itemId} onExit={() => setState("briefing")} />
  );
}
